const express = require('express');
const router = express.Router();
const comicController = require('../controllers/comicController');
const episodeController = require('../controllers/episodeController');
const pageController = require('../controllers/pageController');
const upload = require('../middlewares/upload');
const authController = require('../controllers/authController');
router.get('/user-comics', authController.resolveUser, comicController.getComics);
router.post('/comics', authController.verifyToken, upload.single('image'), comicController.createComic);
router.patch('/comics/:id', authController.verifyToken, upload.single('image'), comicController.updateComic);
router.delete('/comics/:id', authController.verifyToken, comicController.deleteComic);
router.get('/comics/:id/episodes', authController.resolveUser, episodeController.getEpisodes);
router.post('/comics/:id/episodes', authController.verifyToken, episodeController.createEpisode);
router.patch('/comics/:id/episodes/:epId', authController.verifyToken, episodeController.updateEpisode);
router.delete('/comics/:id/episodes/:epId', authController.verifyToken, episodeController.deleteEpisode);
router.post('/comics/:id/episodes/:epId/pages', authController.verifyToken, upload.array('files'), pageController.uploadPages);
router.patch('/comics/:id/episodes/:epId/pages/:pageId', authController.verifyToken, upload.single('file'), pageController.replacePage);
router.delete('/comics/:id/episodes/:epId/pages/:pageId', authController.verifyToken, pageController.deletePage);
module.exports = router;
